### ISSUE TITLE
RevokeMediaStream

### ISSUE THREAD

**Issue by hoene** [Temasys/AdapterJS#177]
Using Chrome Version 49.0.2623.75 unknown (64-bit) on Ubuntu 14.04 and adapter.js 0.13.0, I had some issues calling attachMediaStream(something, null) to detach a media stream.

the error message is 

angular.js:12722 TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at TypeError (native)
    at HTMLVideoElement.Object.defineProperty.set (/bower_components/adapter.js/index.js:630:28)
    at attachMediaStream (/bower_components/adapter.js/index.js:1028:27)
    at attachMediaStream (/bower_components/adapter.js/index.js:1242:5)
    at updateMedia (/src/controllers/meeting-controller.js:291:29)
    at Object.video (/src/services/video-service.js:87:21)

**Comment by johache** [comment]
Pull request opened : https://github.com/Temasys/AdapterJS/pull/178

**Comment by johache** [comment]
Hi,
This issue should be fixed with today's release:
https://github.com/Temasys/AdapterJS/releases/tag/0.13.1

I'm closing the issue, feel free to re-open it if you still see it.
